// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package metadatadb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countUserMetadataStmt, err = db.PrepareContext(ctx, countUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query CountUserMetadata: %w", err)
	}
	if q.createUserMetadataStmt, err = db.PrepareContext(ctx, createUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserMetadata: %w", err)
	}
	if q.deleteAllUserMetadataStmt, err = db.PrepareContext(ctx, deleteAllUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllUserMetadata: %w", err)
	}
	if q.deleteUserMetadataStmt, err = db.PrepareContext(ctx, deleteUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserMetadata: %w", err)
	}
	if q.getUserMetadataStmt, err = db.PrepareContext(ctx, getUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserMetadata: %w", err)
	}
	if q.getUserMetadataByIDStmt, err = db.PrepareContext(ctx, getUserMetadataByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserMetadataByID: %w", err)
	}
	if q.listAllUserMetadataStmt, err = db.PrepareContext(ctx, listAllUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMetadata: %w", err)
	}
	if q.listUserMetadataStmt, err = db.PrepareContext(ctx, listUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMetadata: %w", err)
	}
	if q.updateUserMetadataStmt, err = db.PrepareContext(ctx, updateUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserMetadata: %w", err)
	}
	if q.upsertUserMetadataStmt, err = db.PrepareContext(ctx, upsertUserMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUserMetadata: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countUserMetadataStmt != nil {
		if cerr := q.countUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUserMetadataStmt: %w", cerr)
		}
	}
	if q.createUserMetadataStmt != nil {
		if cerr := q.createUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserMetadataStmt: %w", cerr)
		}
	}
	if q.deleteAllUserMetadataStmt != nil {
		if cerr := q.deleteAllUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllUserMetadataStmt: %w", cerr)
		}
	}
	if q.deleteUserMetadataStmt != nil {
		if cerr := q.deleteUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserMetadataStmt: %w", cerr)
		}
	}
	if q.getUserMetadataStmt != nil {
		if cerr := q.getUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserMetadataStmt: %w", cerr)
		}
	}
	if q.getUserMetadataByIDStmt != nil {
		if cerr := q.getUserMetadataByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserMetadataByIDStmt: %w", cerr)
		}
	}
	if q.listAllUserMetadataStmt != nil {
		if cerr := q.listAllUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMetadataStmt: %w", cerr)
		}
	}
	if q.listUserMetadataStmt != nil {
		if cerr := q.listUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMetadataStmt: %w", cerr)
		}
	}
	if q.updateUserMetadataStmt != nil {
		if cerr := q.updateUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserMetadataStmt: %w", cerr)
		}
	}
	if q.upsertUserMetadataStmt != nil {
		if cerr := q.upsertUserMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserMetadataStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	countUserMetadataStmt     *sql.Stmt
	createUserMetadataStmt    *sql.Stmt
	deleteAllUserMetadataStmt *sql.Stmt
	deleteUserMetadataStmt    *sql.Stmt
	getUserMetadataStmt       *sql.Stmt
	getUserMetadataByIDStmt   *sql.Stmt
	listAllUserMetadataStmt   *sql.Stmt
	listUserMetadataStmt      *sql.Stmt
	updateUserMetadataStmt    *sql.Stmt
	upsertUserMetadataStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		countUserMetadataStmt:     q.countUserMetadataStmt,
		createUserMetadataStmt:    q.createUserMetadataStmt,
		deleteAllUserMetadataStmt: q.deleteAllUserMetadataStmt,
		deleteUserMetadataStmt:    q.deleteUserMetadataStmt,
		getUserMetadataStmt:       q.getUserMetadataStmt,
		getUserMetadataByIDStmt:   q.getUserMetadataByIDStmt,
		listAllUserMetadataStmt:   q.listAllUserMetadataStmt,
		listUserMetadataStmt:      q.listUserMetadataStmt,
		updateUserMetadataStmt:    q.updateUserMetadataStmt,
		upsertUserMetadataStmt:    q.upsertUserMetadataStmt,
	}
}
