// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package metadatadb

import (
	"time"
)

type UserMetadatum struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Key        string    `json:"key"`
	Value      string    `json:"value"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}
