// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package metadatadb

import (
	"context"
)

type Querier interface {
	//CountUserMetadata
	//
	//  SELECT COUNT(*) FROM user_metadata
	//  WHERE user_id = ?
	CountUserMetadata(ctx context.Context, userID int64) (int64, error)
	//CreateUserMetadata
	//
	//  INSERT INTO user_metadata (user_id, key, value)
	//  VALUES (?, ?, ?)
	//  RETURNING id, user_id, "key", value, created_at, modified_at
	CreateUserMetadata(ctx context.Context, arg CreateUserMetadataParams) (UserMetadatum, error)
	//DeleteAllUserMetadata
	//
	//  DELETE FROM user_metadata
	//  WHERE user_id = ?
	DeleteAllUserMetadata(ctx context.Context, userID int64) error
	//DeleteUserMetadata
	//
	//  DELETE FROM user_metadata
	//  WHERE user_id = ? AND key = ?
	DeleteUserMetadata(ctx context.Context, arg DeleteUserMetadataParams) error
	//GetUserMetadata
	//
	//  SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
	//  WHERE user_id = ? AND key = ? LIMIT 1
	GetUserMetadata(ctx context.Context, arg GetUserMetadataParams) (UserMetadatum, error)
	//GetUserMetadataByID
	//
	//  SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
	//  WHERE id = ? LIMIT 1
	GetUserMetadataByID(ctx context.Context, id int64) (UserMetadatum, error)
	//ListAllUserMetadata
	//
	//  SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
	//  ORDER BY user_id, key ASC
	//  LIMIT ? OFFSET ?
	ListAllUserMetadata(ctx context.Context, arg ListAllUserMetadataParams) ([]UserMetadatum, error)
	//ListUserMetadata
	//
	//  SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
	//  WHERE user_id = ?
	//  ORDER BY key ASC
	ListUserMetadata(ctx context.Context, userID int64) ([]UserMetadatum, error)
	//UpdateUserMetadata
	//
	//  UPDATE user_metadata
	//  SET value = ?
	//  WHERE user_id = ? AND key = ?
	//  RETURNING id, user_id, "key", value, created_at, modified_at
	UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) (UserMetadatum, error)
	//UpsertUserMetadata
	//
	//  INSERT INTO user_metadata (user_id, key, value)
	//  VALUES (?, ?, ?)
	//  ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
	//  RETURNING id, user_id, "key", value, created_at, modified_at
	UpsertUserMetadata(ctx context.Context, arg UpsertUserMetadataParams) (UserMetadatum, error)
}

var _ Querier = (*Queries)(nil)
