// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_metadata.sql

package metadatadb

import (
	"context"
)

const countUserMetadata = `-- name: CountUserMetadata :one
SELECT COUNT(*) FROM user_metadata
WHERE user_id = ?
`

// CountUserMetadata
//
//	SELECT COUNT(*) FROM user_metadata
//	WHERE user_id = ?
func (q *Queries) CountUserMetadata(ctx context.Context, userID int64) (int64, error) {
	row := q.queryRow(ctx, q.countUserMetadataStmt, countUserMetadata, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserMetadata = `-- name: CreateUserMetadata :one
INSERT INTO user_metadata (user_id, key, value)
VALUES (?, ?, ?)
RETURNING id, user_id, "key", value, created_at, modified_at
`

type CreateUserMetadataParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

// CreateUserMetadata
//
//	INSERT INTO user_metadata (user_id, key, value)
//	VALUES (?, ?, ?)
//	RETURNING id, user_id, "key", value, created_at, modified_at
func (q *Queries) CreateUserMetadata(ctx context.Context, arg CreateUserMetadataParams) (UserMetadatum, error) {
	row := q.queryRow(ctx, q.createUserMetadataStmt, createUserMetadata, arg.UserID, arg.Key, arg.Value)
	var i UserMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteAllUserMetadata = `-- name: DeleteAllUserMetadata :exec
DELETE FROM user_metadata
WHERE user_id = ?
`

// DeleteAllUserMetadata
//
//	DELETE FROM user_metadata
//	WHERE user_id = ?
func (q *Queries) DeleteAllUserMetadata(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteAllUserMetadataStmt, deleteAllUserMetadata, userID)
	return err
}

const deleteUserMetadata = `-- name: DeleteUserMetadata :exec
DELETE FROM user_metadata
WHERE user_id = ? AND key = ?
`

type DeleteUserMetadataParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

// DeleteUserMetadata
//
//	DELETE FROM user_metadata
//	WHERE user_id = ? AND key = ?
func (q *Queries) DeleteUserMetadata(ctx context.Context, arg DeleteUserMetadataParams) error {
	_, err := q.exec(ctx, q.deleteUserMetadataStmt, deleteUserMetadata, arg.UserID, arg.Key)
	return err
}

const getUserMetadata = `-- name: GetUserMetadata :one
SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
WHERE user_id = ? AND key = ? LIMIT 1
`

type GetUserMetadataParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

// GetUserMetadata
//
//	SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
//	WHERE user_id = ? AND key = ? LIMIT 1
func (q *Queries) GetUserMetadata(ctx context.Context, arg GetUserMetadataParams) (UserMetadatum, error) {
	row := q.queryRow(ctx, q.getUserMetadataStmt, getUserMetadata, arg.UserID, arg.Key)
	var i UserMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserMetadataByID = `-- name: GetUserMetadataByID :one
SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
WHERE id = ? LIMIT 1
`

// GetUserMetadataByID
//
//	SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
//	WHERE id = ? LIMIT 1
func (q *Queries) GetUserMetadataByID(ctx context.Context, id int64) (UserMetadatum, error) {
	row := q.queryRow(ctx, q.getUserMetadataByIDStmt, getUserMetadataByID, id)
	var i UserMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listAllUserMetadata = `-- name: ListAllUserMetadata :many
SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
ORDER BY user_id, key ASC
LIMIT ? OFFSET ?
`

type ListAllUserMetadataParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// ListAllUserMetadata
//
//	SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
//	ORDER BY user_id, key ASC
//	LIMIT ? OFFSET ?
func (q *Queries) ListAllUserMetadata(ctx context.Context, arg ListAllUserMetadataParams) ([]UserMetadatum, error) {
	rows, err := q.query(ctx, q.listAllUserMetadataStmt, listAllUserMetadata, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMetadatum
	for rows.Next() {
		var i UserMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMetadata = `-- name: ListUserMetadata :many
SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
WHERE user_id = ?
ORDER BY key ASC
`

// ListUserMetadata
//
//	SELECT id, user_id, "key", value, created_at, modified_at FROM user_metadata
//	WHERE user_id = ?
//	ORDER BY key ASC
func (q *Queries) ListUserMetadata(ctx context.Context, userID int64) ([]UserMetadatum, error) {
	rows, err := q.query(ctx, q.listUserMetadataStmt, listUserMetadata, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMetadatum
	for rows.Next() {
		var i UserMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserMetadata = `-- name: UpdateUserMetadata :one
UPDATE user_metadata
SET value = ?
WHERE user_id = ? AND key = ?
RETURNING id, user_id, "key", value, created_at, modified_at
`

type UpdateUserMetadataParams struct {
	Value  string `json:"value"`
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

// UpdateUserMetadata
//
//	UPDATE user_metadata
//	SET value = ?
//	WHERE user_id = ? AND key = ?
//	RETURNING id, user_id, "key", value, created_at, modified_at
func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) (UserMetadatum, error) {
	row := q.queryRow(ctx, q.updateUserMetadataStmt, updateUserMetadata, arg.Value, arg.UserID, arg.Key)
	var i UserMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const upsertUserMetadata = `-- name: UpsertUserMetadata :one
INSERT INTO user_metadata (user_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
RETURNING id, user_id, "key", value, created_at, modified_at
`

type UpsertUserMetadataParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

// UpsertUserMetadata
//
//	INSERT INTO user_metadata (user_id, key, value)
//	VALUES (?, ?, ?)
//	ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
//	RETURNING id, user_id, "key", value, created_at, modified_at
func (q *Queries) UpsertUserMetadata(ctx context.Context, arg UpsertUserMetadataParams) (UserMetadatum, error) {
	row := q.queryRow(ctx, q.upsertUserMetadataStmt, upsertUserMetadata, arg.UserID, arg.Key, arg.Value)
	var i UserMetadatum
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
