// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package account

import (
	"time"
)

type User struct {
	ID                   int64     `json:"id"`
	Uuid                 string    `json:"uuid"`
	FirstName            string    `json:"first_name"`
	LastName             string    `json:"last_name"`
	Username             string    `json:"username"`
	PasswordHash         string    `json:"password_hash"`
	UsernamePasswordHash string    `json:"username_password_hash"`
	Email                string    `json:"email"`
	CreatedAt            time.Time `json:"created_at"`
	ModifiedAt           time.Time `json:"modified_at"`
}
