// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package account

import (
	"context"
)

type Querier interface {
	//CountUsers
	//
	//  SELECT COUNT(*) FROM users
	CountUsers(ctx context.Context) (int64, error)
	//CreateUser
	//
	//  INSERT INTO users (
	//      uuid,
	//      first_name,
	//      last_name,
	//      username,
	//      password_hash,
	//      username_password_hash,
	//      email
	//  ) VALUES (
	//      ?, ?, ?, ?, ?, ?, ?
	//  )
	//  RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//DeleteUser
	//
	//  DELETE FROM users
	//  WHERE id = ?
	DeleteUser(ctx context.Context, id int64) error
	//DeleteUserByUUID
	//
	//  DELETE FROM users
	//  WHERE uuid = ?
	DeleteUserByUUID(ctx context.Context, uuid string) error
	//GetUserByEmail
	//
	//  SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
	//  WHERE email = ? LIMIT 1
	GetUserByEmail(ctx context.Context, email string) (User, error)
	//GetUserByID
	//
	//  SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
	//  WHERE id = ? LIMIT 1
	GetUserByID(ctx context.Context, id int64) (User, error)
	//GetUserByUUID
	//
	//  SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
	//  WHERE uuid = ? LIMIT 1
	GetUserByUUID(ctx context.Context, uuid string) (User, error)
	//GetUserByUsername
	//
	//  SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
	//  WHERE username = ? LIMIT 1
	GetUserByUsername(ctx context.Context, username string) (User, error)
	//ListUsers
	//
	//  SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
	//  ORDER BY created_at DESC
	//  LIMIT ? OFFSET ?
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	//UpdateUser
	//
	//  UPDATE users
	//  SET first_name = ?,
	//      last_name = ?,
	//      username = ?,
	//      email = ?
	//  WHERE id = ?
	//  RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	//UpdateUserPassword
	//
	//  UPDATE users
	//  SET password_hash = ?,
	//      username_password_hash = ?
	//  WHERE id = ?
	//  RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	//UserExistsByEmail
	//
	//  SELECT EXISTS(SELECT 1 FROM users WHERE email = ?) AS user_exists
	UserExistsByEmail(ctx context.Context, email string) (int64, error)
	//UserExistsByUsername
	//
	//  SELECT EXISTS(SELECT 1 FROM users WHERE username = ?) AS user_exists
	UserExistsByUsername(ctx context.Context, username string) (int64, error)
}

var _ Querier = (*Queries)(nil)
