// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package account

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

// CountUsers
//
//	SELECT COUNT(*) FROM users
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    uuid,
    first_name,
    last_name,
    username,
    password_hash,
    username_password_hash,
    email
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
`

type CreateUserParams struct {
	Uuid                 string `json:"uuid"`
	FirstName            string `json:"first_name"`
	LastName             string `json:"last_name"`
	Username             string `json:"username"`
	PasswordHash         string `json:"password_hash"`
	UsernamePasswordHash string `json:"username_password_hash"`
	Email                string `json:"email"`
}

// CreateUser
//
//	INSERT INTO users (
//	    uuid,
//	    first_name,
//	    last_name,
//	    username,
//	    password_hash,
//	    username_password_hash,
//	    email
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?
//	)
//	RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.PasswordHash,
		arg.UsernamePasswordHash,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

// DeleteUser
//
//	DELETE FROM users
//	WHERE id = ?
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserByUUID = `-- name: DeleteUserByUUID :exec
DELETE FROM users
WHERE uuid = ?
`

// DeleteUserByUUID
//
//	DELETE FROM users
//	WHERE uuid = ?
func (q *Queries) DeleteUserByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUUID, uuid)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
WHERE email = ? LIMIT 1
`

// GetUserByEmail
//
//	SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
//	WHERE email = ? LIMIT 1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
WHERE id = ? LIMIT 1
`

// GetUserByID
//
//	SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
//	WHERE id = ? LIMIT 1
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
WHERE uuid = ? LIMIT 1
`

// GetUserByUUID
//
//	SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
//	WHERE uuid = ? LIMIT 1
func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
WHERE username = ? LIMIT 1
`

// GetUserByUsername
//
//	SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
//	WHERE username = ? LIMIT 1
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// ListUsers
//
//	SELECT id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at FROM users
//	ORDER BY created_at DESC
//	LIMIT ? OFFSET ?
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.PasswordHash,
			&i.UsernamePasswordHash,
			&i.Email,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = ?,
    last_name = ?,
    username = ?,
    email = ?
WHERE id = ?
RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
`

type UpdateUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	ID        int64  `json:"id"`
}

// UpdateUser
//
//	UPDATE users
//	SET first_name = ?,
//	    last_name = ?,
//	    username = ?,
//	    email = ?
//	WHERE id = ?
//	RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = ?,
    username_password_hash = ?
WHERE id = ?
RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
`

type UpdateUserPasswordParams struct {
	PasswordHash         string `json:"password_hash"`
	UsernamePasswordHash string `json:"username_password_hash"`
	ID                   int64  `json:"id"`
}

// UpdateUserPassword
//
//	UPDATE users
//	SET password_hash = ?,
//	    username_password_hash = ?
//	WHERE id = ?
//	RETURNING id, uuid, first_name, last_name, username, password_hash, username_password_hash, email, created_at, modified_at
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.UsernamePasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.UsernamePasswordHash,
		&i.Email,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ?) AS user_exists
`

// UserExistsByEmail
//
//	SELECT EXISTS(SELECT 1 FROM users WHERE email = ?) AS user_exists
func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExistsByEmail, email)
	var user_exists int64
	err := row.Scan(&user_exists)
	return user_exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = ?) AS user_exists
`

// UserExistsByUsername
//
//	SELECT EXISTS(SELECT 1 FROM users WHERE username = ?) AS user_exists
func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExistsByUsername, username)
	var user_exists int64
	err := row.Scan(&user_exists)
	return user_exists, err
}
